# Generated by Django 2.1.7 on 2019-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190316_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='personality_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Influential Person'),
        ),
    ]
